services:
  textpod:
    image: namvu87/textpod-toc:latest
    build: .
    ports:
      - '3000:3000'
    volumes:
      - './data:/app'
    container_name: textpod-daisyui
    restart: unless-stopped